name: '20 - CrePython 20 test of CreGeoReference'
on:
  workflow_dispatch:
  schedule:
#    daily,on 5:20  #m h d/m m d/w 
    - cron:  '20 5 * * 0'

# sudo docker container run  --volume ./:/cre/python/CreGeoReference  --workdir /cre/python/CreGeoReference/ credocker/crepython:2020.0 /cre/python/CreGeoReference/test_local.sh

jobs:
  versions:
    runs-on: ubuntu-latest
    container:
      image: credocker/crepython:2020.0
      env:
#        NEWSAPI_KEY:  ${{ secrets.NEWSAPI_KEY }}
#        RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }}
        GEONAMES_KEY: ${{ secrets.GEONAMES_KEY }}  
#      volumes:
#        - ${{ github.workspace }}:/cre/python/CreGeoReference

    outputs:
      pkg_version: ${{ steps.pkg-version.outputs.PKG_VERSION }}
    steps:
    - uses: actions/checkout@v4
    - name: Set version
      id: pkg-version
      run: echo "PKG_VERSION=$(grep -m 1 version pyproject.toml | tr -s ' ' | tr -d '"' | tr -d "'" | cut -d' ' -f3)" >> "$GITHUB_OUTPUT"

    - name: Run tests locally
      run: ./test_local.sh




